### ISSUE TITLE
0927 le lendemain

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#10]
**Décrivez le bug**
Plutôt une modification, il faudrait rajouter un fondu en noir et faire en sorte que le mot "Le lendemain" s'affiche en plein écran (écran noir) avant de repasser sur le fond du grenier et de continuer pour mieux marquer la délimitation. (ligne 0927)

**Le reproduir**
Les étapes pou reproduire le bug:
1. Allez à '...'
2. Cliquez sur '....'
3. Scrollez vers le bas jusqu'à '....'
4. Voyez l'erreur

**Comportement attendu**
Une description claire et concise de ce qui était censé ce produire

**Screenshots**
https://puu.sh/BCUxj.jpg

**Configuration :**

**Autres commentaires**
Ajoutez ici d'autres commentaires sur le problème

**Comment by shobu13** [comment]
quel fichier ?
