### ISSUE TITLE
transition prologue -salle

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#13]
**Décrivez le bug**
pas un bug, mais changer la transition en rajoutant un fondu en noir et un titre : "Le travail en salle"

**Le reproduir**
Les étapes pou reproduire le bug:
1. Allez à '...'
2. Cliquez sur '....'
3. Scrollez vers le bas jusqu'à '....'
4. Voyez l'erreur

**Comportement attendu**
Une description claire et concise de ce qui était censé ce produire

**Screenshots**
Si possible, un screenshot pour aider à comprendre le problème

**Configuration :**

**Autres commentaires**
Ajoutez ici d'autres commentaires sur le problème

**Comment by shobu13** [comment]
![image](https://user-images.githubusercontent.com/21972673/46504824-6054fa00-c82f-11e8-8062-fc721c1ecfde.png)
