### ISSUE TITLE
Ch1 Salle 683

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#18]
**Décrivez le bug**
juste après le changement ligne 0683 il y a un espèce de petit temps d'une demiseconde de freeze, il faudrait rajouter un fondu en noir

**Le reproduir**
Les étapes pou reproduire le bug:
1. Allez à '...'
2. Cliquez sur '....'
3. Scrollez vers le bas jusqu'à '....'
4. Voyez l'erreur

**Comportement attendu**
Une description claire et concise de ce qui était censé ce produire

**Screenshots**
Si possible, un screenshot pour aider à comprendre le problème

**Configuration :**

**Autres commentaires**
Ajoutez ici d'autres commentaires sur le problème

**Comment by shobu13** [comment]
Pas compris
