### ISSUE TITLE
ch02 akié pas de fondu en noir l0509

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#24]
**Décrivez le bug**
pas de fondu à la ligne 0509 du chapitre 2 akié

**Le reproduir**
Les étapes pou reproduire le bug:
1. Allez à '...'
2. Cliquez sur '....'
3. Scrollez vers le bas jusqu'à '....'
4. Voyez l'erreur

**Comportement attendu**
Une description claire et concise de ce qui était censé ce produire

**Screenshots**
https://puu.sh/BDqI5.jpg

**Configuration :**

**Autres commentaires**
Ajoutez ici d'autres commentaires sur le problème

**Comment by shobu13** [comment]
Corriger, à retester
