### ISSUE TITLE
bug background

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#7]
**Décrivez le bug**
background qui ne s'affiche pas à la ligne 0685

**Le reproduir**
Les étapes pou reproduire le bug:
1. Allez à '...'
2. Cliquez sur '....'
3. Scrollez vers le bas jusqu'à '....'
4. Voyez l'erreur

**Comportement attendu**
background rue qui ne s'affiche pas

**Screenshots**
http://puu.sh/BCUha.png

**Configuration :**

**Autres commentaires**
Le bckground est noté "ruelle" alors que ça devrait être "rue"

**Comment by shobu13** [comment]
quel fichier ?
