### ISSUE TITLE
0857 sourcils clateau 

### ISSUE THREAD

**Issue by Catablor** [shobu13/Meiji#8]
**Décrivez le bug**
Les sourcils de Clateau ne s'affichent pas

**Le reproduire**
ligne 0857

**Comportement attendu**
les sourcils devraient s'afficher

**Screenshots**
https://puu.sh/BCUos.jpg

**Configuration :**

**Autres commentaires**
Ajoutez ici d'autres commentaires sur le problème

**Comment by shobu13** [comment]
quel fichier ?
